package com.demo.validation.domain;

import lombok.Data;

/**
 * 设备台账对象 DeviceLedger
 * Generated by aicodegen.
 */
@Data
public class DeviceLedger {
    private static final long serialVersionUID = 1L;

    /**
     * TODO: add fields
     */
}
