package com.demo.validation.domain;

import lombok.Data;

/**
 * 标识验证记录对象 NoticeRecord
 * Generated by aicodegen.
 */
@Data
public class NoticeRecord {
    private static final long serialVersionUID = 1L;

    /**
     * TODO: add fields
     */
}
