package com.demo.validation.domain;

import lombok.Data;

/**
 * 生成证明记录对象 ProofRecord
 * Generated by aicodegen.
 */
@Data
public class ProofRecord {
    private static final long serialVersionUID = 1L;

    /**
     * TODO: add fields
     */
}
