package com.demo.validation.controller;

import java.util.List;
import com.demo.validation.domain.DeviceLedger;
import com.demo.validation.pojo.bo.DeviceLedgerBo;
import com.demo.validation.pojo.vo.DeviceLedgerVo;
import com.demo.validation.service.IDeviceLedgerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.ResponseEntity;

/**
 * 设备台账Controller
 * Generated by aicodegen.
 */
@RestController
@RequestMapping("/device-ledger")
public class DeviceLedgerController {
    @Autowired
    private IDeviceLedgerService deviceLedgerService;

    @GetMapping("/list")
    public ResponseEntity<List<DeviceLedgerVo>> list(DeviceLedgerBo query) {
        return ResponseEntity.ok(deviceLedgerService.selectDeviceLedgerList(query));
    }

    @GetMapping(value = "/{id}")
    public ResponseEntity<DeviceLedger> getInfo(@PathVariable("id") Long id) {
        return ResponseEntity.ok(deviceLedgerService.selectDeviceLedgerById(id));
    }

    @PostMapping
    public ResponseEntity<Integer> add(@RequestBody DeviceLedgerBo command) {
        return ResponseEntity.ok(deviceLedgerService.insertDeviceLedger(command));
    }

    @PutMapping
    public ResponseEntity<Integer> edit(@RequestBody DeviceLedgerBo command) {
        return ResponseEntity.ok(deviceLedgerService.updateDeviceLedger(command));
    }

    @DeleteMapping("/{ids}")
    public ResponseEntity<Integer> remove(@PathVariable Long[] ids) {
        return ResponseEntity.ok(deviceLedgerService.deleteDeviceLedgerByIds(ids));
    }
}
