package com.demo.validation.controller;

import java.util.List;
import com.demo.validation.domain.NoticeRecord;
import com.demo.validation.pojo.bo.NoticeRecordBo;
import com.demo.validation.pojo.vo.NoticeRecordVo;
import com.demo.validation.service.INoticeRecordService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.ResponseEntity;

/**
 * 标识验证记录Controller
 * Generated by aicodegen.
 */
@RestController
@RequestMapping("/notice-record")
public class NoticeRecordController {
    @Autowired
    private INoticeRecordService noticeRecordService;

    @GetMapping("/list")
    public ResponseEntity<List<NoticeRecordVo>> list(NoticeRecordBo query) {
        return ResponseEntity.ok(noticeRecordService.selectNoticeRecordList(query));
    }

    @GetMapping(value = "/{id}")
    public ResponseEntity<NoticeRecord> getInfo(@PathVariable("id") Long id) {
        return ResponseEntity.ok(noticeRecordService.selectNoticeRecordById(id));
    }

    @PostMapping
    public ResponseEntity<Integer> add(@RequestBody NoticeRecordBo command) {
        return ResponseEntity.ok(noticeRecordService.insertNoticeRecord(command));
    }

    @PutMapping
    public ResponseEntity<Integer> edit(@RequestBody NoticeRecordBo command) {
        return ResponseEntity.ok(noticeRecordService.updateNoticeRecord(command));
    }

    @DeleteMapping("/{ids}")
    public ResponseEntity<Integer> remove(@PathVariable Long[] ids) {
        return ResponseEntity.ok(noticeRecordService.deleteNoticeRecordByIds(ids));
    }
}
