package com.demo.validation.controller;

import java.util.List;
import com.demo.validation.domain.ProofRecord;
import com.demo.validation.pojo.bo.ProofRecordBo;
import com.demo.validation.pojo.vo.ProofRecordVo;
import com.demo.validation.service.IProofRecordService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.ResponseEntity;

/**
 * 生成证明记录Controller
 * Generated by aicodegen.
 */
@RestController
@RequestMapping("/proof-record")
public class ProofRecordController {
    @Autowired
    private IProofRecordService proofRecordService;

    @GetMapping("/list")
    public ResponseEntity<List<ProofRecordVo>> list(ProofRecordBo query) {
        return ResponseEntity.ok(proofRecordService.selectProofRecordList(query));
    }

    @GetMapping(value = "/{id}")
    public ResponseEntity<ProofRecord> getInfo(@PathVariable("id") Long id) {
        return ResponseEntity.ok(proofRecordService.selectProofRecordById(id));
    }

    @PostMapping
    public ResponseEntity<Integer> add(@RequestBody ProofRecordBo command) {
        return ResponseEntity.ok(proofRecordService.insertProofRecord(command));
    }

    @PutMapping
    public ResponseEntity<Integer> edit(@RequestBody ProofRecordBo command) {
        return ResponseEntity.ok(proofRecordService.updateProofRecord(command));
    }

    @DeleteMapping("/{ids}")
    public ResponseEntity<Integer> remove(@PathVariable Long[] ids) {
        return ResponseEntity.ok(proofRecordService.deleteProofRecordByIds(ids));
    }
}
