package com.demo.validation.controller;

import java.util.List;
import com.demo.validation.domain.SqlNoticeRecord;
import com.demo.validation.pojo.bo.SqlNoticeRecordBo;
import com.demo.validation.pojo.vo.SqlNoticeRecordVo;
import com.demo.validation.service.ISqlNoticeRecordService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.ResponseEntity;

/**
 * SQL通知记录Controller
 * Generated by aicodegen.
 */
@RestController
@RequestMapping("/sql-notice-record")
public class SqlNoticeRecordController {
    @Autowired
    private ISqlNoticeRecordService sqlNoticeRecordService;

    @GetMapping("/list")
    public ResponseEntity<List<SqlNoticeRecordVo>> list(SqlNoticeRecordBo query) {
        return ResponseEntity.ok(sqlNoticeRecordService.selectSqlNoticeRecordList(query));
    }

    @GetMapping(value = "/{id}")
    public ResponseEntity<SqlNoticeRecord> getInfo(@PathVariable("id") Long id) {
        return ResponseEntity.ok(sqlNoticeRecordService.selectSqlNoticeRecordById(id));
    }

    @PostMapping
    public ResponseEntity<Integer> add(@RequestBody SqlNoticeRecordBo command) {
        return ResponseEntity.ok(sqlNoticeRecordService.insertSqlNoticeRecord(command));
    }

    @PutMapping
    public ResponseEntity<Integer> edit(@RequestBody SqlNoticeRecordBo command) {
        return ResponseEntity.ok(sqlNoticeRecordService.updateSqlNoticeRecord(command));
    }

    @DeleteMapping("/{ids}")
    public ResponseEntity<Integer> remove(@PathVariable Long[] ids) {
        return ResponseEntity.ok(sqlNoticeRecordService.deleteSqlNoticeRecordByIds(ids));
    }
}
