package com.demo.validation.service.impl;

import java.util.List;
import com.demo.validation.mapper.DeviceLedgerMapper;
import com.demo.validation.domain.DeviceLedger;
import com.demo.validation.pojo.bo.DeviceLedgerBo;
import com.demo.validation.pojo.vo.DeviceLedgerVo;
import com.demo.validation.service.IDeviceLedgerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * DeviceLedgerServiceImpl
 * Generated by aicodegen.
 */
@Service
public class DeviceLedgerServiceImpl implements IDeviceLedgerService {
    @Autowired
    private DeviceLedgerMapper deviceLedgerMapper;

    @Override
    public DeviceLedger selectDeviceLedgerById(Long id) {
        return deviceLedgerMapper.selectDeviceLedgerById(id);
    }

    @Override
    public List<DeviceLedgerVo> selectDeviceLedgerList(DeviceLedgerBo query) {
        return deviceLedgerMapper.selectDeviceLedgerList(query);
    }

    @Override
    public int insertDeviceLedger(DeviceLedgerBo command) {
        return deviceLedgerMapper.insertDeviceLedger(command);
    }

    @Override
    public int updateDeviceLedger(DeviceLedgerBo command) {
        return deviceLedgerMapper.updateDeviceLedger(command);
    }

    @Override
    public int deleteDeviceLedgerByIds(Long[] ids) {
        return deviceLedgerMapper.deleteDeviceLedgerByIds(ids);
    }

    @Override
    public int deleteDeviceLedgerById(Long id) {
        return deviceLedgerMapper.deleteDeviceLedgerById(id);
    }
}
