package com.demo.validation.service.impl;

import java.util.List;
import com.demo.validation.mapper.NoticeRecordMapper;
import com.demo.validation.domain.NoticeRecord;
import com.demo.validation.pojo.bo.NoticeRecordBo;
import com.demo.validation.pojo.vo.NoticeRecordVo;
import com.demo.validation.service.INoticeRecordService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * NoticeRecordServiceImpl
 * Generated by aicodegen.
 */
@Service
public class NoticeRecordServiceImpl implements INoticeRecordService {
    @Autowired
    private NoticeRecordMapper noticeRecordMapper;

    @Override
    public NoticeRecord selectNoticeRecordById(Long id) {
        return noticeRecordMapper.selectNoticeRecordById(id);
    }

    @Override
    public List<NoticeRecordVo> selectNoticeRecordList(NoticeRecordBo query) {
        return noticeRecordMapper.selectNoticeRecordList(query);
    }

    @Override
    public int insertNoticeRecord(NoticeRecordBo command) {
        return noticeRecordMapper.insertNoticeRecord(command);
    }

    @Override
    public int updateNoticeRecord(NoticeRecordBo command) {
        return noticeRecordMapper.updateNoticeRecord(command);
    }

    @Override
    public int deleteNoticeRecordByIds(Long[] ids) {
        return noticeRecordMapper.deleteNoticeRecordByIds(ids);
    }

    @Override
    public int deleteNoticeRecordById(Long id) {
        return noticeRecordMapper.deleteNoticeRecordById(id);
    }
}
