package com.demo.validation.service.impl;

import java.util.List;
import com.demo.validation.mapper.ProofRecordMapper;
import com.demo.validation.domain.ProofRecord;
import com.demo.validation.pojo.bo.ProofRecordBo;
import com.demo.validation.pojo.vo.ProofRecordVo;
import com.demo.validation.service.IProofRecordService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * ProofRecordServiceImpl
 * Generated by aicodegen.
 */
@Service
public class ProofRecordServiceImpl implements IProofRecordService {
    @Autowired
    private ProofRecordMapper proofRecordMapper;

    @Override
    public ProofRecord selectProofRecordById(Long id) {
        return proofRecordMapper.selectProofRecordById(id);
    }

    @Override
    public List<ProofRecordVo> selectProofRecordList(ProofRecordBo query) {
        return proofRecordMapper.selectProofRecordList(query);
    }

    @Override
    public int insertProofRecord(ProofRecordBo command) {
        return proofRecordMapper.insertProofRecord(command);
    }

    @Override
    public int updateProofRecord(ProofRecordBo command) {
        return proofRecordMapper.updateProofRecord(command);
    }

    @Override
    public int deleteProofRecordByIds(Long[] ids) {
        return proofRecordMapper.deleteProofRecordByIds(ids);
    }

    @Override
    public int deleteProofRecordById(Long id) {
        return proofRecordMapper.deleteProofRecordById(id);
    }
}
