package com.demo.validation.service.impl;

import java.util.List;
import com.demo.validation.mapper.SqlNoticeRecordMapper;
import com.demo.validation.domain.SqlNoticeRecord;
import com.demo.validation.pojo.bo.SqlNoticeRecordBo;
import com.demo.validation.pojo.vo.SqlNoticeRecordVo;
import com.demo.validation.service.ISqlNoticeRecordService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * SqlNoticeRecordServiceImpl
 * Generated by aicodegen.
 */
@Service
public class SqlNoticeRecordServiceImpl implements ISqlNoticeRecordService {
    @Autowired
    private SqlNoticeRecordMapper sqlNoticeRecordMapper;

    @Override
    public SqlNoticeRecord selectSqlNoticeRecordById(Long id) {
        return sqlNoticeRecordMapper.selectSqlNoticeRecordById(id);
    }

    @Override
    public List<SqlNoticeRecordVo> selectSqlNoticeRecordList(SqlNoticeRecordBo query) {
        return sqlNoticeRecordMapper.selectSqlNoticeRecordList(query);
    }

    @Override
    public int insertSqlNoticeRecord(SqlNoticeRecordBo command) {
        return sqlNoticeRecordMapper.insertSqlNoticeRecord(command);
    }

    @Override
    public int updateSqlNoticeRecord(SqlNoticeRecordBo command) {
        return sqlNoticeRecordMapper.updateSqlNoticeRecord(command);
    }

    @Override
    public int deleteSqlNoticeRecordByIds(Long[] ids) {
        return sqlNoticeRecordMapper.deleteSqlNoticeRecordByIds(ids);
    }

    @Override
    public int deleteSqlNoticeRecordById(Long id) {
        return sqlNoticeRecordMapper.deleteSqlNoticeRecordById(id);
    }
}
