package com.demo.validation.mapper;

import java.util.List;
import com.demo.validation.domain.DeviceLedger;
import com.demo.validation.pojo.bo.DeviceLedgerBo;
import com.demo.validation.pojo.vo.DeviceLedgerVo;

/**
 * DeviceLedgerMapper
 * Generated by aicodegen.
 */
public interface DeviceLedgerMapper {
    DeviceLedger selectDeviceLedgerById(Long id);

    List<DeviceLedgerVo> selectDeviceLedgerList(DeviceLedgerBo query);

    int insertDeviceLedger(DeviceLedgerBo command);

    int updateDeviceLedger(DeviceLedgerBo command);

    int deleteDeviceLedgerById(Long id);

    int deleteDeviceLedgerByIds(Long[] ids);
}
