package com.demo.validation.mapper;

import java.util.List;
import com.demo.validation.domain.NoticeRecord;
import com.demo.validation.pojo.bo.NoticeRecordBo;
import com.demo.validation.pojo.vo.NoticeRecordVo;

/**
 * NoticeRecordMapper
 * Generated by aicodegen.
 */
public interface NoticeRecordMapper {
    NoticeRecord selectNoticeRecordById(Long id);

    List<NoticeRecordVo> selectNoticeRecordList(NoticeRecordBo query);

    int insertNoticeRecord(NoticeRecordBo command);

    int updateNoticeRecord(NoticeRecordBo command);

    int deleteNoticeRecordById(Long id);

    int deleteNoticeRecordByIds(Long[] ids);
}
