package com.demo.validation.mapper;

import java.util.List;
import com.demo.validation.domain.ProofRecord;
import com.demo.validation.pojo.bo.ProofRecordBo;
import com.demo.validation.pojo.vo.ProofRecordVo;

/**
 * ProofRecordMapper
 * Generated by aicodegen.
 */
public interface ProofRecordMapper {
    ProofRecord selectProofRecordById(Long id);

    List<ProofRecordVo> selectProofRecordList(ProofRecordBo query);

    int insertProofRecord(ProofRecordBo command);

    int updateProofRecord(ProofRecordBo command);

    int deleteProofRecordById(Long id);

    int deleteProofRecordByIds(Long[] ids);
}
