package com.demo.validation.mapper;

import java.util.List;
import com.demo.validation.domain.SqlNoticeRecord;
import com.demo.validation.pojo.bo.SqlNoticeRecordBo;
import com.demo.validation.pojo.vo.SqlNoticeRecordVo;

/**
 * SqlNoticeRecordMapper
 * Generated by aicodegen.
 */
public interface SqlNoticeRecordMapper {
    SqlNoticeRecord selectSqlNoticeRecordById(Long id);

    List<SqlNoticeRecordVo> selectSqlNoticeRecordList(SqlNoticeRecordBo query);

    int insertSqlNoticeRecord(SqlNoticeRecordBo command);

    int updateSqlNoticeRecord(SqlNoticeRecordBo command);

    int deleteSqlNoticeRecordById(Long id);

    int deleteSqlNoticeRecordByIds(Long[] ids);
}
