package com.demo.validation.pojo.bo;

import java.io.Serializable;
import lombok.Data;

/**
 * 设备台账业务对象 DeviceLedgerBo
 * Generated by aicodegen.
 */
@Data
public class DeviceLedgerBo implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * TODO: add fields
     */
}
