package com.demo.validation.pojo.bo;

import java.io.Serializable;
import lombok.Data;

/**
 * 标识验证记录业务对象 NoticeRecordBo
 * Generated by aicodegen.
 */
@Data
public class NoticeRecordBo implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * TODO: add fields
     */
}
