package com.demo.validation.pojo.bo;

import java.io.Serializable;
import lombok.Data;

/**
 * 生成证明记录业务对象 ProofRecordBo
 * Generated by aicodegen.
 */
@Data
public class ProofRecordBo implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * TODO: add fields
     */
}
