package com.demo.validation.pojo.bo;

import java.io.Serializable;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * SQL通知记录业务对象 SqlNoticeRecordBo
 * Generated by aicodegen.
 */
@Data
public class SqlNoticeRecordBo implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 主键ID
     */
    private Long id;

    /**
     * 通知标题
     */
    private String noticeTitle;

    /**
     * 通知金额
     */
    private BigDecimal noticeAmount;

    /**
     * 启用标识
     */
    private Integer enabledFlag;

    /**
     * 创建时间
     */
    private LocalDateTime createTime;
}
