package com.demo.validation.pojo.vo;

import java.io.Serializable;
import lombok.Data;

/**
 * 设备台账视图对象 DeviceLedgerVo
 * Generated by aicodegen.
 */
@Data
public class DeviceLedgerVo implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * TODO: add fields
     */
}
