package com.demo.validation.pojo.vo;

import java.io.Serializable;
import lombok.Data;

/**
 * 标识验证记录视图对象 NoticeRecordVo
 * Generated by aicodegen.
 */
@Data
public class NoticeRecordVo implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * TODO: add fields
     */
}
