package com.demo.validation.pojo.vo;

import java.io.Serializable;
import lombok.Data;

/**
 * 生成证明记录视图对象 ProofRecordVo
 * Generated by aicodegen.
 */
@Data
public class ProofRecordVo implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * TODO: add fields
     */
}
