package com.demo.validation.service;

import java.util.List;
import com.demo.validation.domain.DeviceLedger;
import com.demo.validation.pojo.bo.DeviceLedgerBo;
import com.demo.validation.pojo.vo.DeviceLedgerVo;

/**
 * DeviceLedgerService
 * Generated by aicodegen.
 */
public interface IDeviceLedgerService {
    DeviceLedger selectDeviceLedgerById(Long id);

    List<DeviceLedgerVo> selectDeviceLedgerList(DeviceLedgerBo query);

    int insertDeviceLedger(DeviceLedgerBo command);

    int updateDeviceLedger(DeviceLedgerBo command);

    int deleteDeviceLedgerByIds(Long[] ids);

    int deleteDeviceLedgerById(Long id);
}
