package com.demo.validation.service;

import java.util.List;
import com.demo.validation.domain.NoticeRecord;
import com.demo.validation.pojo.bo.NoticeRecordBo;
import com.demo.validation.pojo.vo.NoticeRecordVo;

/**
 * NoticeRecordService
 * Generated by aicodegen.
 */
public interface INoticeRecordService {
    NoticeRecord selectNoticeRecordById(Long id);

    List<NoticeRecordVo> selectNoticeRecordList(NoticeRecordBo query);

    int insertNoticeRecord(NoticeRecordBo command);

    int updateNoticeRecord(NoticeRecordBo command);

    int deleteNoticeRecordByIds(Long[] ids);

    int deleteNoticeRecordById(Long id);
}
