package com.demo.validation.service;

import java.util.List;
import com.demo.validation.domain.ProofRecord;
import com.demo.validation.pojo.bo.ProofRecordBo;
import com.demo.validation.pojo.vo.ProofRecordVo;

/**
 * ProofRecordService
 * Generated by aicodegen.
 */
public interface IProofRecordService {
    ProofRecord selectProofRecordById(Long id);

    List<ProofRecordVo> selectProofRecordList(ProofRecordBo query);

    int insertProofRecord(ProofRecordBo command);

    int updateProofRecord(ProofRecordBo command);

    int deleteProofRecordByIds(Long[] ids);

    int deleteProofRecordById(Long id);
}
