package com.demo.validation.service;

import java.util.List;
import com.demo.validation.domain.SqlNoticeRecord;
import com.demo.validation.pojo.bo.SqlNoticeRecordBo;
import com.demo.validation.pojo.vo.SqlNoticeRecordVo;

/**
 * SqlNoticeRecordService
 * Generated by aicodegen.
 */
public interface ISqlNoticeRecordService {
    SqlNoticeRecord selectSqlNoticeRecordById(Long id);

    List<SqlNoticeRecordVo> selectSqlNoticeRecordList(SqlNoticeRecordBo query);

    int insertSqlNoticeRecord(SqlNoticeRecordBo command);

    int updateSqlNoticeRecord(SqlNoticeRecordBo command);

    int deleteSqlNoticeRecordByIds(Long[] ids);

    int deleteSqlNoticeRecordById(Long id);
}
